# Obtén y conoce tus datos



### 1. Importa las librerías necesarias

In [2]:
import numpy as np
import pandas as pd

### 2. Importa el dataset de este [enlace](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/u.user) y guárdalo en una variable llamada users. Usa pd.read_csv()

In [3]:
users = pd.read_csv("https://raw.githubusercontent.com/justmarkham/DAT8/master/data/u.user", sep="|")
users

     user_id  age gender     occupation zip_code
0          1   24      M     technician    85711
1          2   53      F          other    94043
2          3   23      M         writer    32067
3          4   24      M     technician    43537
4          5   33      F          other    15213
..       ...  ...    ...            ...      ...
938      939   26      F        student    33319
939      940   32      M  administrator    02215
940      941   20      M        student    97229
941      942   48      F      librarian    78209
942      943   22      M        student    77841

[943 rows x 5 columns]

In [4]:
users = pd.read_csv("https://raw.githubusercontent.com/justmarkham/DAT8/master/data/u.user", sep="|")
users

     user_id  age gender     occupation zip_code
0          1   24      M     technician    85711
1          2   53      F          other    94043
2          3   23      M         writer    32067
3          4   24      M     technician    43537
4          5   33      F          other    15213
..       ...  ...    ...            ...      ...
938      939   26      F        student    33319
939      940   32      M  administrator    02215
940      941   20      M        student    97229
941      942   48      F      librarian    78209
942      943   22      M        student    77841

[943 rows x 5 columns]

### 3. Muestra las 25 primeros registros

In [5]:
users[0:26:1]

    user_id  age gender     occupation zip_code
0         1   24      M     technician    85711
1         2   53      F          other    94043
2         3   23      M         writer    32067
3         4   24      M     technician    43537
4         5   33      F          other    15213
5         6   42      M      executive    98101
6         7   57      M  administrator    91344
7         8   36      M  administrator    05201
8         9   29      M        student    01002
9        10   53      M         lawyer    90703
10       11   39      F          other    30329
11       12   28      F          other    06405
12       13   47      M       educator    29206
13       14   45      M      scientist    55106
14       15   49      F       educator    97301
15       16   21      M  entertainment    10309
16       17   30      M     programmer    06355
17       18   35      F          other    37212
18       19   40      M      librarian    02138
19       20   42      F      homemaker    95660
20       21   26      M         writer    30068
21       22   25      M         writer    40206
22       23   30      F         artist    48197
23       24   21      F         artist    94533
24       25   39      M       engineer    55107
25       26   49      M       engineer    21044

### 4. Muestra las 25 primeros registros de otra forma

In [6]:
users.head(25)

    user_id  age gender     occupation zip_code
0         1   24      M     technician    85711
1         2   53      F          other    94043
2         3   23      M         writer    32067
3         4   24      M     technician    43537
4         5   33      F          other    15213
5         6   42      M      executive    98101
6         7   57      M  administrator    91344
7         8   36      M  administrator    05201
8         9   29      M        student    01002
9        10   53      M         lawyer    90703
10       11   39      F          other    30329
11       12   28      F          other    06405
12       13   47      M       educator    29206
13       14   45      M      scientist    55106
14       15   49      F       educator    97301
15       16   21      M  entertainment    10309
16       17   30      M     programmer    06355
17       18   35      F          other    37212
18       19   40      M      librarian    02138
19       20   42      F      homemaker    95660
20       21   26      M         writer    30068
21       22   25      M         writer    40206
22       23   30      F         artist    48197
23       24   21      F         artist    94533
24       25   39      M       engineer    55107

### 5. Muestra los últimos 25 registros

In [7]:
users[-1:-26:-1]

     user_id  age gender     occupation zip_code
942      943   22      M        student    77841
941      942   48      F      librarian    78209
940      941   20      M        student    97229
939      940   32      M  administrator    02215
938      939   26      F        student    33319
937      938   38      F     technician    55038
936      937   48      M       educator    98072
935      936   24      M          other    32789
934      935   42      M         doctor    66221
933      934   61      M       engineer    22902
932      933   28      M        student    48105
931      932   58      M       educator    06437
930      931   60      M       educator    33556
929      930   28      F      scientist    07310
928      929   44      M      scientist    53711
927      928   21      M        student    55408
926      927   23      M     programmer    55428
925      926   49      M  entertainment    01701
924      925   18      F       salesman    49036
923      924   29      M          other    11753
922      923   21      M        student    E2E3R
921      922   29      F  administrator    21114
920      921   20      F        student    98801
919      920   30      F         artist    90008
918      919   25      M          other    14216

In [ ]:
users.tail(25) # otra manera.

     user_id  age gender     occupation zip_code
918      919   25      M          other    14216
919      920   30      F         artist    90008
920      921   20      F        student    98801
921      922   29      F  administrator    21114
922      923   21      M        student    E2E3R
923      924   29      M          other    11753
924      925   18      F       salesman    49036
925      926   49      M  entertainment    01701
926      927   23      M     programmer    55428
927      928   21      M        student    55408
928      929   44      M      scientist    53711
929      930   28      F      scientist    07310
930      931   60      M       educator    33556
931      932   58      M       educator    06437
932      933   28      M        student    48105
933      934   61      M       engineer    22902
934      935   42      M         doctor    66221
935      936   24      M          other    32789
936      937   48      M       educator    98072
937      938   38      F     technician    55038
938      939   26      F        student    33319
939      940   32      M  administrator    02215
940      941   20      M        student    97229
941      942   48      F      librarian    78209
942      943   22      M        student    77841

### 6. Cuántos registros hay en total en este dataset?
Resuélvelo de al menos dos formas diferentes

In [18]:
registros_total = len(users)
registros_total

943

In [ ]:
total_registros = users.shape[0] # devuelve una tupla y de esa tupla quierp el número de filas (la primera posición del atributo shape).el numero de filas esta en la primera posicion por eso pongo index 0.
print(total_registros)

943

### 7. Cuántas columnas hay en total en este dataset?
Resuélvelo de al menos dos formas diferentes

In [ ]:
total_columns = users.shape[1] # index 1 de la tupla que me devuelve el shape que  hace referencia a la primera columna.
total_columns

5

In [21]:
total_columns = len(users.columns)
total_columns

5

### 8. Haz un print de cada uno de los nombres de las columnas

In [22]:
for columna in users.columns:
    print(columna)

user_id
age
gender
occupation
zip_code

### 9. Accede al índice, a los nombres de las columnas y a los valores por separado

In [26]:
print(users.index)
print(users.columns)
print(users.values)

RangeIndex(start=0, stop=943, step=1)
Index(['user_id', 'age', 'gender', 'occupation', 'zip_code'], dtype='str')
[[1 24 'M' 'technician' '85711']
 [2 53 'F' 'other' '94043']
 [3 23 'M' 'writer' '32067']
 ...
 [941 20 'M' 'student' '97229']
 [942 48 'F' 'librarian' '78209']
 [943 22 'M' 'student' '77841']]

In [12]:
#otra manera
list(users.index)

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 184,
 185,
 186,
 187,
 188,
 189,
 190,
 191,
 192,
 193,
 194,
 195,
 196,
 197,
 198,
 199,
 200,
 201,
 202,
 203,
 204,
 205,
 206,
 207,
 208,
 209,
 210,
 211,
 212,
 213,
 214,
 215,
 216,
 217,
 218,
 219,
 220,
 221,
 222,
 223,
 224,
 225,
 226,
 227,
 228,
 229,
 230,
 231,
 232,
 233,
 234,
 235,
 236,
 237,
 238,
 239,
 240,
 241,
 242,
 243,
 244,
 245,
 246,
 247,
 248,
 249,
 250,
 251,
 252,
 253,
 254,
 255,
 256,
 257,
 258,
 259,
 260,
 261,
 262,
 263,
 264,
 265,
 266,
 267,
 268,
 269,
 270,
 271,
 272,
 273,
 274,
 275,
 276,
 277,
 278,
 279,
 280,
 281,
 282,
 283,
 284,
 285,
 286,
 287,
 288,
 289,
 290,
 291,
 292,
 293,
 294,
 295,
 296,
 297,
 298,
 299,
 300,
 301,
 302,
 303,
 304,
 305,
 306,
 307,
 308,
 309,
 310,
 311,
 312,
 313,
 314,
 315,
 316,
 317,
 318,
 319,
 320,
 321,
 322,
 323,
 324,
 325,
 326,
 327,
 328,
 329,
 330,
 331,
 332,
 333,
 334,
 335,
 336,
 337,
 338,
 339,
 340,
 341,
 342,
 343,
 344,
 345,
 346,
 347,
 348,
 349,
 350,
 351,
 352,
 353,
 354,
 355,
 356,
 357,
 358,
 359,
 360,
 361,
 362,
 363,
 364,
 365,
 366,
 367,
 368,
 369,
 370,
 371,
 372,
 373,
 374,
 375,
 376,
 377,
 378,
 379,
 380,
 381,
 382,
 383,
 384,
 385,
 386,
 387,
 388,
 389,
 390,
 391,
 392,
 393,
 394,
 395,
 396,
 397,
 398,
 399,
 400,
 401,
 402,
 403,
 404,
 405,
 406,
 407,
 408,
 409,
 410,
 411,
 412,
 413,
 414,
 415,
 416,
 417,
 418,
 419,
 420,
 421,
 422,
 423,
 424,
 425,
 426,
 427,
 428,
 429,
 430,
 431,
 432,
 433,
 434,
 435,
 436,
 437,
 438,
 439,
 440,
 441,
 442,
 443,
 444,
 445,
 446,
 447,
 448,
 449,
 450,
 451,
 452,
 453,
 454,
 455,
 456,
 457,
 458,
 459,
 460,
 461,
 462,
 463,
 464,
 465,
 466,
 467,
 468,
 469,
 470,
 471,
 472,
 473,
 474,
 475,
 476,
 477,
 478,
 479,
 480,
 481,
 482,
 483,
 484,
 485,
 486,
 487,
 488,
 489,
 490,
 491,
 492,
 493,
 494,
 495,
 496,
 497,
 498,
 499,
 500,
 501,
 502,
 503,
 504,
 505,
 506,
 507,
 508,
 509,
 510,
 511,
 512,
 513,
 514,
 515,
 516,
 517,
 518,
 519,
 520,
 521,
 522,
 523,
 524,
 525,
 526,
 527,
 528,
 529,
 530,
 531,
 532,
 533,
 534,
 535,
 536,
 537,
 538,
 539,
 540,
 541,
 542,
 543,
 544,
 545,
 546,
 547,
 548,
 549,
 550,
 551,
 552,
 553,
 554,
 555,
 556,
 557,
 558,
 559,
 560,
 561,
 562,
 563,
 564,
 565,
 566,
 567,
 568,
 569,
 570,
 571,
 572,
 573,
 574,
 575,
 576,
 577,
 578,
 579,
 580,
 581,
 582,
 583,
 584,
 585,
 586,
 587,
 588,
 589,
 590,
 591,
 592,
 593,
 594,
 595,
 596,
 597,
 598,
 599,
 600,
 601,
 602,
 603,
 604,
 605,
 606,
 607,
 608,
 609,
 610,
 611,
 612,
 613,
 614,
 615,
 616,
 617,
 618,
 619,
 620,
 621,
 622,
 623,
 624,
 625,
 626,
 627,
 628,
 629,
 630,
 631,
 632,
 633,
 634,
 635,
 636,
 637,
 638,
 639,
 640,
 641,
 642,
 643,
 644,
 645,
 646,
 647,
 648,
 649,
 650,
 651,
 652,
 653,
 654,
 655,
 656,
 657,
 658,
 659,
 660,
 661,
 662,
 663,
 664,
 665,
 666,
 667,
 668,
 669,
 670,
 671,
 672,
 673,
 674,
 675,
 676,
 677,
 678,
 679,
 680,
 681,
 682,
 683,
 684,
 685,
 686,
 687,
 688,
 689,
 690,
 691,
 692,
 693,
 694,
 695,
 696,
 697,
 698,
 699,
 700,
 701,
 702,
 703,
 704,
 705,
 706,
 707,
 708,
 709,
 710,
 711,
 712,
 713,
 714,
 715,
 716,
 717,
 718,
 719,
 720,
 721,
 722,
 723,
 724,
 725,
 726,
 727,
 728,
 729,
 730,
 731,
 732,
 733,
 734,
 735,
 736,
 737,
 738,
 739,
 740,
 741,
 742,
 743,
 744,
 745,
 746,
 747,
 748,
 749,
 750,
 751,
 752,
 753,
 754,
 755,
 756,
 757,
 758,
 759,
 760,
 761,
 762,
 763,
 764,
 765,
 766,
 767,
 768,
 769,
 770,
 771,
 772,
 773,
 774,
 775,
 776,
 777,
 778,
 779,
 780,
 781,
 782,
 783,
 784,
 785,
 786,
 787,
 788,
 789,
 790,
 791,
 792,
 793,
 794,
 795,
 796,
 797,
 798,
 799,
 800,
 801,
 802,
 803,
 804,
 805,
 806,
 807,
 808,
 809,
 810,
 811,
 812,
 813,
 814,
 815,
 816,
 817,
 818,
 819,
 820,
 821,
 822,
 823,
 824,
 825,
 826,
 827,
 828,
 829,
 830,
 831,
 832,
 833,
 834,
 835,
 836,
 837,
 838,
 839,
 840,
 841,
 842,
 843,
 844,
 845,
 846,
 847,
 848,
 849,
 850,
 851,
 852,
 853,
 854,
 855,
 856,
 857,
 858,
 859,
 860,
 861,
 862,
 863,
 864,
 865,
 866,
 867,
 868,
 869,
 870,
 871,
 872,
 873,
 874,
 875,
 876,
 877,
 878,
 879,
 880,
 881,
 882,
 883,
 884,
 885,
 886,
 887,
 888,
 889,
 890,
 891,
 892,
 893,
 894,
 895,
 896,
 897,
 898,
 899,
 900,
 901,
 902,
 903,
 904,
 905,
 906,
 907,
 908,
 909,
 910,
 911,
 912,
 913,
 914,
 915,
 916,
 917,
 918,
 919,
 920,
 921,
 922,
 923,
 924,
 925,
 926,
 927,
 928,
 929,
 930,
 931,
 932,
 933,
 934,
 935,
 936,
 937,
 938,
 939,
 940,
 941,
 942]

In [13]:
list(users.columns)

['user_id', 'age', 'gender', 'occupation', 'zip_code']

In [14]:
list(users.values)

[array([1, 24, 'M', 'technician', '85711'], dtype=object),
 array([2, 53, 'F', 'other', '94043'], dtype=object),
 array([3, 23, 'M', 'writer', '32067'], dtype=object),
 array([4, 24, 'M', 'technician', '43537'], dtype=object),
 array([5, 33, 'F', 'other', '15213'], dtype=object),
 array([6, 42, 'M', 'executive', '98101'], dtype=object),
 array([7, 57, 'M', 'administrator', '91344'], dtype=object),
 array([8, 36, 'M', 'administrator', '05201'], dtype=object),
 array([9, 29, 'M', 'student', '01002'], dtype=object),
 array([10, 53, 'M', 'lawyer', '90703'], dtype=object),
 array([11, 39, 'F', 'other', '30329'], dtype=object),
 array([12, 28, 'F', 'other', '06405'], dtype=object),
 array([13, 47, 'M', 'educator', '29206'], dtype=object),
 array([14, 45, 'M', 'scientist', '55106'], dtype=object),
 array([15, 49, 'F', 'educator', '97301'], dtype=object),
 array([16, 21, 'M', 'entertainment', '10309'], dtype=object),
 array([17, 30, 'M', 'programmer', '06355'], dtype=object),
 array([18, 35, 'F', 'other', '37212'], dtype=object),
 array([19, 40, 'M', 'librarian', '02138'], dtype=object),
 array([20, 42, 'F', 'homemaker', '95660'], dtype=object),
 array([21, 26, 'M', 'writer', '30068'], dtype=object),
 array([22, 25, 'M', 'writer', '40206'], dtype=object),
 array([23, 30, 'F', 'artist', '48197'], dtype=object),
 array([24, 21, 'F', 'artist', '94533'], dtype=object),
 array([25, 39, 'M', 'engineer', '55107'], dtype=object),
 array([26, 49, 'M', 'engineer', '21044'], dtype=object),
 array([27, 40, 'F', 'librarian', '30030'], dtype=object),
 array([28, 32, 'M', 'writer', '55369'], dtype=object),
 array([29, 41, 'M', 'programmer', '94043'], dtype=object),
 array([30, 7, 'M', 'student', '55436'], dtype=object),
 array([31, 24, 'M', 'artist', '10003'], dtype=object),
 array([32, 28, 'F', 'student', '78741'], dtype=object),
 array([33, 23, 'M', 'student', '27510'], dtype=object),
 array([34, 38, 'F', 'administrator', '42141'], dtype=object),
 array([35, 20, 'F', 'homemaker', '42459'], dtype=object),
 array([36, 19, 'F', 'student', '93117'], dtype=object),
 array([37, 23, 'M', 'student', '55105'], dtype=object),
 array([38, 28, 'F', 'other', '54467'], dtype=object),
 array([39, 41, 'M', 'entertainment', '01040'], dtype=object),
 array([40, 38, 'M', 'scientist', '27514'], dtype=object),
 array([41, 33, 'M', 'engineer', '80525'], dtype=object),
 array([42, 30, 'M', 'administrator', '17870'], dtype=object),
 array([43, 29, 'F', 'librarian', '20854'], dtype=object),
 array([44, 26, 'M', 'technician', '46260'], dtype=object),
 array([45, 29, 'M', 'programmer', '50233'], dtype=object),
 array([46, 27, 'F', 'marketing', '46538'], dtype=object),
 array([47, 53, 'M', 'marketing', '07102'], dtype=object),
 array([48, 45, 'M', 'administrator', '12550'], dtype=object),
 array([49, 23, 'F', 'student', '76111'], dtype=object),
 array([50, 21, 'M', 'writer', '52245'], dtype=object),
 array([51, 28, 'M', 'educator', '16509'], dtype=object),
 array([52, 18, 'F', 'student', '55105'], dtype=object),
 array([53, 26, 'M', 'programmer', '55414'], dtype=object),
 array([54, 22, 'M', 'executive', '66315'], dtype=object),
 array([55, 37, 'M', 'programmer', '01331'], dtype=object),
 array([56, 25, 'M', 'librarian', '46260'], dtype=object),
 array([57, 16, 'M', 'none', '84010'], dtype=object),
 array([58, 27, 'M', 'programmer', '52246'], dtype=object),
 array([59, 49, 'M', 'educator', '08403'], dtype=object),
 array([60, 50, 'M', 'healthcare', '06472'], dtype=object),
 array([61, 36, 'M', 'engineer', '30040'], dtype=object),
 array([62, 27, 'F', 'administrator', '97214'], dtype=object),
 array([63, 31, 'M', 'marketing', '75240'], dtype=object),
 array([64, 32, 'M', 'educator', '43202'], dtype=object),
 array([65, 51, 'F', 'educator', '48118'], dtype=object),
 array([66, 23, 'M', 'student', '80521'], dtype=object),
 array([67, 17, 'M', 'student', '60402'], dtype=object),
 array([68, 19, 'M', 'student', '22904'], dtype=object),
 array([69, 24, 'M', 'engineer', '55337'], dtype=object),
 array([70, 27, 'M', 'engineer', '60067'], dtype=object),
 array([71, 39, 'M', 'scientist', '98034'], dtype=object),
 array([72, 48, 'F', 'administrator', '73034'], dtype=object),
 array([73, 24, 'M', 'student', '41850'], dtype=object),
 array([74, 39, 'M', 'scientist', 'T8H1N'], dtype=object),
 array([75, 24, 'M', 'entertainment', '08816'], dtype=object),
 array([76, 20, 'M', 'student', '02215'], dtype=object),
 array([77, 30, 'M', 'technician', '29379'], dtype=object),
 array([78, 26, 'M', 'administrator', '61801'], dtype=object),
 array([79, 39, 'F', 'administrator', '03755'], dtype=object),
 array([80, 34, 'F', 'administrator', '52241'], dtype=object),
 array([81, 21, 'M', 'student', '21218'], dtype=object),
 array([82, 50, 'M', 'programmer', '22902'], dtype=object),
 array([83, 40, 'M', 'other', '44133'], dtype=object),
 array([84, 32, 'M', 'executive', '55369'], dtype=object),
 array([85, 51, 'M', 'educator', '20003'], dtype=object),
 array([86, 26, 'M', 'administrator', '46005'], dtype=object),
 array([87, 47, 'M', 'administrator', '89503'], dtype=object),
 array([88, 49, 'F', 'librarian', '11701'], dtype=object),
 array([89, 43, 'F', 'administrator', '68106'], dtype=object),
 array([90, 60, 'M', 'educator', '78155'], dtype=object),
 array([91, 55, 'M', 'marketing', '01913'], dtype=object),
 array([92, 32, 'M', 'entertainment', '80525'], dtype=object),
 array([93, 48, 'M', 'executive', '23112'], dtype=object),
 array([94, 26, 'M', 'student', '71457'], dtype=object),
 array([95, 31, 'M', 'administrator', '10707'], dtype=object),
 array([96, 25, 'F', 'artist', '75206'], dtype=object),
 array([97, 43, 'M', 'artist', '98006'], dtype=object),
 array([98, 49, 'F', 'executive', '90291'], dtype=object),
 array([99, 20, 'M', 'student', '63129'], dtype=object),
 array([100, 36, 'M', 'executive', '90254'], dtype=object),
 array([101, 15, 'M', 'student', '05146'], dtype=object),
 array([102, 38, 'M', 'programmer', '30220'], dtype=object),
 array([103, 26, 'M', 'student', '55108'], dtype=object),
 array([104, 27, 'M', 'student', '55108'], dtype=object),
 array([105, 24, 'M', 'engineer', '94043'], dtype=object),
 array([106, 61, 'M', 'retired', '55125'], dtype=object),
 array([107, 39, 'M', 'scientist', '60466'], dtype=object),
 array([108, 44, 'M', 'educator', '63130'], dtype=object),
 array([109, 29, 'M', 'other', '55423'], dtype=object),
 array([110, 19, 'M', 'student', '77840'], dtype=object),
 array([111, 57, 'M', 'engineer', '90630'], dtype=object),
 array([112, 30, 'M', 'salesman', '60613'], dtype=object),
 array([113, 47, 'M', 'executive', '95032'], dtype=object),
 array([114, 27, 'M', 'programmer', '75013'], dtype=object),
 array([115, 31, 'M', 'engineer', '17110'], dtype=object),
 array([116, 40, 'M', 'healthcare', '97232'], dtype=object),
 array([117, 20, 'M', 'student', '16125'], dtype=object),
 array([118, 21, 'M', 'administrator', '90210'], dtype=object),
 array([119, 32, 'M', 'programmer', '67401'], dtype=object),
 array([120, 47, 'F', 'other', '06260'], dtype=object),
 array([121, 54, 'M', 'librarian', '99603'], dtype=object),
 array([122, 32, 'F', 'writer', '22206'], dtype=object),
 array([123, 48, 'F', 'artist', '20008'], dtype=object),
 array([124, 34, 'M', 'student', '60615'], dtype=object),
 array([125, 30, 'M', 'lawyer', '22202'], dtype=object),
 array([126, 28, 'F', 'lawyer', '20015'], dtype=object),
 array([127, 33, 'M', 'none', '73439'], dtype=object),
 array([128, 24, 'F', 'marketing', '20009'], dtype=object),
 array([129, 36, 'F', 'marketing', '07039'], dtype=object),
 array([130, 20, 'M', 'none', '60115'], dtype=object),
 array([131, 59, 'F', 'administrator', '15237'], dtype=object),
 array([132, 24, 'M', 'other', '94612'], dtype=object),
 array([133, 53, 'M', 'engineer', '78602'], dtype=object),
 array([134, 31, 'M', 'programmer', '80236'], dtype=object),
 array([135, 23, 'M', 'student', '38401'], dtype=object),
 array([136, 51, 'M', 'other', '97365'], dtype=object),
 array([137, 50, 'M', 'educator', '84408'], dtype=object),
 array([138, 46, 'M', 'doctor', '53211'], dtype=object),
 array([139, 20, 'M', 'student', '08904'], dtype=object),
 array([140, 30, 'F', 'student', '32250'], dtype=object),
 array([141, 49, 'M', 'programmer', '36117'], dtype=object),
 array([142, 13, 'M', 'other', '48118'], dtype=object),
 array([143, 42, 'M', 'technician', '08832'], dtype=object),
 array([144, 53, 'M', 'programmer', '20910'], dtype=object),
 array([145, 31, 'M', 'entertainment', 'V3N4P'], dtype=object),
 array([146, 45, 'M', 'artist', '83814'], dtype=object),
 array([147, 40, 'F', 'librarian', '02143'], dtype=object),
 array([148, 33, 'M', 'engineer', '97006'], dtype=object),
 array([149, 35, 'F', 'marketing', '17325'], dtype=object),
 array([150, 20, 'F', 'artist', '02139'], dtype=object),
 array([151, 38, 'F', 'administrator', '48103'], dtype=object),
 array([152, 33, 'F', 'educator', '68767'], dtype=object),
 array([153, 25, 'M', 'student', '60641'], dtype=object),
 array([154, 25, 'M', 'student', '53703'], dtype=object),
 array([155, 32, 'F', 'other', '11217'], dtype=object),
 array([156, 25, 'M', 'educator', '08360'], dtype=object),
 array([157, 57, 'M', 'engineer', '70808'], dtype=object),
 array([158, 50, 'M', 'educator', '27606'], dtype=object),
 array([159, 23, 'F', 'student', '55346'], dtype=object),
 array([160, 27, 'M', 'programmer', '66215'], dtype=object),
 array([161, 50, 'M', 'lawyer', '55104'], dtype=object),
 array([162, 25, 'M', 'artist', '15610'], dtype=object),
 array([163, 49, 'M', 'administrator', '97212'], dtype=object),
 array([164, 47, 'M', 'healthcare', '80123'], dtype=object),
 array([165, 20, 'F', 'other', '53715'], dtype=object),
 array([166, 47, 'M', 'educator', '55113'], dtype=object),
 array([167, 37, 'M', 'other', 'L9G2B'], dtype=object),
 array([168, 48, 'M', 'other', '80127'], dtype=object),
 array([169, 52, 'F', 'other', '53705'], dtype=object),
 array([170, 53, 'F', 'healthcare', '30067'], dtype=object),
 array([171, 48, 'F', 'educator', '78750'], dtype=object),
 array([172, 55, 'M', 'marketing', '22207'], dtype=object),
 array([173, 56, 'M', 'other', '22306'], dtype=object),
 array([174, 30, 'F', 'administrator', '52302'], dtype=object),
 array([175, 26, 'F', 'scientist', '21911'], dtype=object),
 array([176, 28, 'M', 'scientist', '07030'], dtype=object),
 array([177, 20, 'M', 'programmer', '19104'], dtype=object),
 array([178, 26, 'M', 'other', '49512'], dtype=object),
 array([179, 15, 'M', 'entertainment', '20755'], dtype=object),
 array([180, 22, 'F', 'administrator', '60202'], dtype=object),
 array([181, 26, 'M', 'executive', '21218'], dtype=object),
 array([182, 36, 'M', 'programmer', '33884'], dtype=object),
 array([183, 33, 'M', 'scientist', '27708'], dtype=object),
 array([184, 37, 'M', 'librarian', '76013'], dtype=object),
 array([185, 53, 'F', 'librarian', '97403'], dtype=object),
 array([186, 39, 'F', 'executive', '00000'], dtype=object),
 array([187, 26, 'M', 'educator', '16801'], dtype=object),
 array([188, 42, 'M', 'student', '29440'], dtype=object),
 array([189, 32, 'M', 'artist', '95014'], dtype=object),
 array([190, 30, 'M', 'administrator', '95938'], dtype=object),
 array([191, 33, 'M', 'administrator', '95161'], dtype=object),
 array([192, 42, 'M', 'educator', '90840'], dtype=object),
 array([193, 29, 'M', 'student', '49931'], dtype=object),
 array([194, 38, 'M', 'administrator', '02154'], dtype=object),
 array([195, 42, 'M', 'scientist', '93555'], dtype=object),
 array([196, 49, 'M', 'writer', '55105'], dtype=object),
 array([197, 55, 'M', 'technician', '75094'], dtype=object),
 array([198, 21, 'F', 'student', '55414'], dtype=object),
 array([199, 30, 'M', 'writer', '17604'], dtype=object),
 array([200, 40, 'M', 'programmer', '93402'], dtype=object),
 array([201, 27, 'M', 'writer', 'E2A4H'], dtype=object),
 array([202, 41, 'F', 'educator', '60201'], dtype=object),
 array([203, 25, 'F', 'student', '32301'], dtype=object),
 array([204, 52, 'F', 'librarian', '10960'], dtype=object),
 array([205, 47, 'M', 'lawyer', '06371'], dtype=object),
 array([206, 14, 'F', 'student', '53115'], dtype=object),
 array([207, 39, 'M', 'marketing', '92037'], dtype=object),
 array([208, 43, 'M', 'engineer', '01720'], dtype=object),
 array([209, 33, 'F', 'educator', '85710'], dtype=object),
 array([210, 39, 'M', 'engineer', '03060'], dtype=object),
 array([211, 66, 'M', 'salesman', '32605'], dtype=object),
 array([212, 49, 'F', 'educator', '61401'], dtype=object),
 array([213, 33, 'M', 'executive', '55345'], dtype=object),
 array([214, 26, 'F', 'librarian', '11231'], dtype=object),
 array([215, 35, 'M', 'programmer', '63033'], dtype=object),
 array([216, 22, 'M', 'engineer', '02215'], dtype=object),
 array([217, 22, 'M', 'other', '11727'], dtype=object),
 array([218, 37, 'M', 'administrator', '06513'], dtype=object),
 array([219, 32, 'M', 'programmer', '43212'], dtype=object),
 array([220, 30, 'M', 'librarian', '78205'], dtype=object),
 array([221, 19, 'M', 'student', '20685'], dtype=object),
 array([222, 29, 'M', 'programmer', '27502'], dtype=object),
 array([223, 19, 'F', 'student', '47906'], dtype=object),
 array([224, 31, 'F', 'educator', '43512'], dtype=object),
 array([225, 51, 'F', 'administrator', '58202'], dtype=object),
 array([226, 28, 'M', 'student', '92103'], dtype=object),
 array([227, 46, 'M', 'executive', '60659'], dtype=object),
 array([228, 21, 'F', 'student', '22003'], dtype=object),
 array([229, 29, 'F', 'librarian', '22903'], dtype=object),
 array([230, 28, 'F', 'student', '14476'], dtype=object),
 array([231, 48, 'M', 'librarian', '01080'], dtype=object),
 array([232, 45, 'M', 'scientist', '99709'], dtype=object),
 array([233, 38, 'M', 'engineer', '98682'], dtype=object),
 array([234, 60, 'M', 'retired', '94702'], dtype=object),
 array([235, 37, 'M', 'educator', '22973'], dtype=object),
 array([236, 44, 'F', 'writer', '53214'], dtype=object),
 array([237, 49, 'M', 'administrator', '63146'], dtype=object),
 array([238, 42, 'F', 'administrator', '44124'], dtype=object),
 array([239, 39, 'M', 'artist', '95628'], dtype=object),
 array([240, 23, 'F', 'educator', '20784'], dtype=object),
 array([241, 26, 'F', 'student', '20001'], dtype=object),
 array([242, 33, 'M', 'educator', '31404'], dtype=object),
 array([243, 33, 'M', 'educator', '60201'], dtype=object),
 array([244, 28, 'M', 'technician', '80525'], dtype=object),
 array([245, 22, 'M', 'student', '55109'], dtype=object),
 array([246, 19, 'M', 'student', '28734'], dtype=object),
 array([247, 28, 'M', 'engineer', '20770'], dtype=object),
 array([248, 25, 'M', 'student', '37235'], dtype=object),
 array([249, 25, 'M', 'student', '84103'], dtype=object),
 array([250, 29, 'M', 'executive', '95110'], dtype=object),
 array([251, 28, 'M', 'doctor', '85032'], dtype=object),
 array([252, 42, 'M', 'engineer', '07733'], dtype=object),
 array([253, 26, 'F', 'librarian', '22903'], dtype=object),
 array([254, 44, 'M', 'educator', '42647'], dtype=object),
 array([255, 23, 'M', 'entertainment', '07029'], dtype=object),
 array([256, 35, 'F', 'none', '39042'], dtype=object),
 array([257, 17, 'M', 'student', '77005'], dtype=object),
 array([258, 19, 'F', 'student', '77801'], dtype=object),
 array([259, 21, 'M', 'student', '48823'], dtype=object),
 array([260, 40, 'F', 'artist', '89801'], dtype=object),
 array([261, 28, 'M', 'administrator', '85202'], dtype=object),
 array([262, 19, 'F', 'student', '78264'], dtype=object),
 array([263, 41, 'M', 'programmer', '55346'], dtype=object),
 array([264, 36, 'F', 'writer', '90064'], dtype=object),
 array([265, 26, 'M', 'executive', '84601'], dtype=object),
 array([266, 62, 'F', 'administrator', '78756'], dtype=object),
 array([267, 23, 'M', 'engineer', '83716'], dtype=object),
 array([268, 24, 'M', 'engineer', '19422'], dtype=object),
 array([269, 31, 'F', 'librarian', '43201'], dtype=object),
 array([270, 18, 'F', 'student', '63119'], dtype=object),
 array([271, 51, 'M', 'engineer', '22932'], dtype=object),
 array([272, 33, 'M', 'scientist', '53706'], dtype=object),
 array([273, 50, 'F', 'other', '10016'], dtype=object),
 array([274, 20, 'F', 'student', '55414'], dtype=object),
 array([275, 38, 'M', 'engineer', '92064'], dtype=object),
 array([276, 21, 'M', 'student', '95064'], dtype=object),
 array([277, 35, 'F', 'administrator', '55406'], dtype=object),
 array([278, 37, 'F', 'librarian', '30033'], dtype=object),
 array([279, 33, 'M', 'programmer', '85251'], dtype=object),
 array([280, 30, 'F', 'librarian', '22903'], dtype=object),
 array([281, 15, 'F', 'student', '06059'], dtype=object),
 array([282, 22, 'M', 'administrator', '20057'], dtype=object),
 array([283, 28, 'M', 'programmer', '55305'], dtype=object),
 array([284, 40, 'M', 'executive', '92629'], dtype=object),
 array([285, 25, 'M', 'programmer', '53713'], dtype=object),
 array([286, 27, 'M', 'student', '15217'], dtype=object),
 array([287, 21, 'M', 'salesman', '31211'], dtype=object),
 array([288, 34, 'M', 'marketing', '23226'], dtype=object),
 array([289, 11, 'M', 'none', '94619'], dtype=object),
 array([290, 40, 'M', 'engineer', '93550'], dtype=object),
 array([291, 19, 'M', 'student', '44106'], dtype=object),
 array([292, 35, 'F', 'programmer', '94703'], dtype=object),
 array([293, 24, 'M', 'writer', '60804'], dtype=object),
 array([294, 34, 'M', 'technician', '92110'], dtype=object),
 array([295, 31, 'M', 'educator', '50325'], dtype=object),
 array([296, 43, 'F', 'administrator', '16803'], dtype=object),
 array([297, 29, 'F', 'educator', '98103'], dtype=object),
 array([298, 44, 'M', 'executive', '01581'], dtype=object),
 array([299, 29, 'M', 'doctor', '63108'], dtype=object),
 array([300, 26, 'F', 'programmer', '55106'], dtype=object),
 array([301, 24, 'M', 'student', '55439'], dtype=object),
 array([302, 42, 'M', 'educator', '77904'], dtype=object),
 array([303, 19, 'M', 'student', '14853'], dtype=object),
 array([304, 22, 'F', 'student', '71701'], dtype=object),
 array([305, 23, 'M', 'programmer', '94086'], dtype=object),
 array([306, 45, 'M', 'other', '73132'], dtype=object),
 array([307, 25, 'M', 'student', '55454'], dtype=object),
 array([308, 60, 'M', 'retired', '95076'], dtype=object),
 array([309, 40, 'M', 'scientist', '70802'], dtype=object),
 array([310, 37, 'M', 'educator', '91711'], dtype=object),
 array([311, 32, 'M', 'technician', '73071'], dtype=object),
 array([312, 48, 'M', 'other', '02110'], dtype=object),
 array([313, 41, 'M', 'marketing', '60035'], dtype=object),
 array([314, 20, 'F', 'student', '08043'], dtype=object),
 array([315, 31, 'M', 'educator', '18301'], dtype=object),
 array([316, 43, 'F', 'other', '77009'], dtype=object),
 array([317, 22, 'M', 'administrator', '13210'], dtype=object),
 array([318, 65, 'M', 'retired', '06518'], dtype=object),
 array([319, 38, 'M', 'programmer', '22030'], dtype=object),
 array([320, 19, 'M', 'student', '24060'], dtype=object),
 array([321, 49, 'F', 'educator', '55413'], dtype=object),
 array([322, 20, 'M', 'student', '50613'], dtype=object),
 array([323, 21, 'M', 'student', '19149'], dtype=object),
 array([324, 21, 'F', 'student', '02176'], dtype=object),
 array([325, 48, 'M', 'technician', '02139'], dtype=object),
 array([326, 41, 'M', 'administrator', '15235'], dtype=object),
 array([327, 22, 'M', 'student', '11101'], dtype=object),
 array([328, 51, 'M', 'administrator', '06779'], dtype=object),
 array([329, 48, 'M', 'educator', '01720'], dtype=object),
 array([330, 35, 'F', 'educator', '33884'], dtype=object),
 array([331, 33, 'M', 'entertainment', '91344'], dtype=object),
 array([332, 20, 'M', 'student', '40504'], dtype=object),
 array([333, 47, 'M', 'other', 'V0R2M'], dtype=object),
 array([334, 32, 'M', 'librarian', '30002'], dtype=object),
 array([335, 45, 'M', 'executive', '33775'], dtype=object),
 array([336, 23, 'M', 'salesman', '42101'], dtype=object),
 array([337, 37, 'M', 'scientist', '10522'], dtype=object),
 array([338, 39, 'F', 'librarian', '59717'], dtype=object),

### 10. Cuál es el tipo de cada columna del dataset?
Hazlo de dos formas diferentes

In [ ]:
print(users.dtypes)

user_id       int64
age           int64
gender          str
occupation      str
zip_code        str
dtype: object

In [16]:
#otra manera
users.info()

<class 'pandas.DataFrame'>
RangeIndex: 943 entries, 0 to 942
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   user_id     943 non-null    int64
 1   age         943 non-null    int64
 2   gender      943 non-null    str
 3   occupation  943 non-null    str
 4   zip_code    943 non-null    str
dtypes: int64(2), str(3)
memory usage: 37.0 KB

In [18]:
#ni idea la otra.

### 11. Haz un print solo de la columna de occupation
Hazlo de dos formas diferentes

In [19]:
users['occupation']

0         technician
1              other
2             writer
3         technician
4              other
           ...
938          student
939    administrator
940          student
941        librarian
942          student
Name: occupation, Length: 943, dtype: str

In [20]:
users.occupation

0         technician
1              other
2             writer
3         technician
4              other
           ...
938          student
939    administrator
940          student
941        librarian
942          student
Name: occupation, Length: 943, dtype: str

### 12. ¿Cuántas profesiones diferentes hay? ¿Y personas por profesión?

In [21]:
users["occupation"].unique()

<StringArray>
[   'technician',         'other',        'writer',     'executive',
 'administrator',       'student',        'lawyer',      'educator',
     'scientist', 'entertainment',    'programmer',     'librarian',
     'homemaker',        'artist',      'engineer',     'marketing',
          'none',    'healthcare',       'retired',      'salesman',
        'doctor']
Length: 21, dtype: str

### 13. ¿Cuál es la profesión más común?

In [ ]:
users["occupation"].mode()

0    student
Name: occupation, dtype: str

### 14. Obtén un resumen de las principales medidas estadísticas de las variables numéricas.  Usa describe()

In [ ]:
users.describe().T # cuando tengo muchas columnas, el .T me lo traspone.

         count        mean         std  min    25%    50%    75%    max
user_id  943.0  472.000000  272.364951  1.0  236.5  472.0  707.5  943.0
age      943.0   34.051962   12.192740  7.0   25.0   31.0   43.0   73.0

### 15. Obtén un resumen de las principales medidas estadísticas de todas las variables.  Usa describe()

In [ ]:
users.describe(include = "all") #incluir variables no numericas.

           user_id         age gender occupation zip_code
count   943.000000  943.000000    943        943      943
unique         NaN         NaN      2         21      795
top            NaN         NaN      M    student    55414
freq           NaN         NaN    670        196        9
mean    472.000000   34.051962    NaN        NaN      NaN
std     272.364951   12.192740    NaN        NaN      NaN
min       1.000000    7.000000    NaN        NaN      NaN
25%     236.500000   25.000000    NaN        NaN      NaN
50%     472.000000   31.000000    NaN        NaN      NaN
75%     707.500000   43.000000    NaN        NaN      NaN
max     943.000000   73.000000    NaN        NaN      NaN

### 16. Obtén un resumen de las principales medidas estadísticas de solo la columna occupation.  Usa describe()

In [28]:
users.occupation.describe()

count         943
unique         21
top       student
freq          196
Name: occupation, dtype: object

### 17. ¿Cuál es la edad media?

In [30]:
users.age.mean()
print(users.age.mean())

34.05196182396607

### 18. ¿Cuál es la edad menos frecuente?

In [ ]:
users.age.value_counts().idxmin() #idxmin nos deuelve el indice, osea en que fila esta el valor minimo.

np.int64(7)

In [ ]:
edad = users["age"].value_counts() 
print(edad[edad == edad.min()]) # me devuelve todos los valore sque cuplen esta condicion,

age
7     1
66    1
11    1
10    1
73    1
Name: count, dtype: int64