### Importa los datos
Dataset con diferentes fármacos, sus efectos y ratings de los clientes.

Importa el dataset *drugLibTrain_raw.tsv*

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from ydata_profiling import ProfileReport # con este import te hace el EDA DE MANERA AUTOMATICA.

c:\Users\tifaw\AppData\Local\Programs\Python\Python311\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
C:\Users\tifaw\AppData\Local\Temp\ipykernel_17632\3896203777.py:5: DeprecationWarning:
    `import ydata_profiling` is deprecated and will not receive more updates.
    Please install fg-data-profiling via `pip install fg-data-profiling` and use `import data_profiling` instead.

  from ydata_profiling import ProfileReport # con este import te hace el EDA DE MANERA AUTOMATICA.

In [3]:
df = pd.read_csv(r"data\drugLibTrain_raw.tsv", sep = '\t')
df.head()

,Unnamed: 0,urlDrugName,rating,effectiveness,sideEffects,condition,benefitsReview,sideEffectsReview,commentsReview
0,2202,enalapril,4,Highly Effective,Mild Side Effects,management of congestive heart failure,slowed the progression of left ventricular dys...,"cough, hypotension , proteinuria, impotence , ...","monitor blood pressure , weight and asses for ..."
1,3117,ortho-tri-cyclen,1,Highly Effective,Severe Side Effects,birth prevention,Although this type of birth control has more c...,"Heavy Cycle, Cramps, Hot Flashes, Fatigue, Lon...","I Hate This Birth Control, I Would Not Suggest..."
2,1146,ponstel,10,Highly Effective,No Side Effects,menstrual cramps,I was used to having cramps so badly that they...,Heavier bleeding and clotting than normal.,I took 2 pills at the onset of my menstrual cr...
3,3947,prilosec,3,Marginally Effective,Mild Side Effects,acid reflux,The acid reflux went away for a few months aft...,"Constipation, dry mouth and some mild dizzines...",I was given Prilosec prescription at a dose of...
4,1951,lyrica,2,Marginally Effective,Severe Side Effects,fibromyalgia,I think that the Lyrica was starting to help w...,I felt extremely drugged and dopey. Could not...,See above

### Descriptive Analysis

Quedate únicamente con las columnas que podamos manejar: Columnas numéricas y columnas categóricas con pocas categorías (menos de 10)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3107 entries, 0 to 3106
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0         3107 non-null   int64
 1   urlDrugName        3107 non-null   object
 2   rating             3107 non-null   int64
 3   effectiveness      3107 non-null   object
 4   sideEffects        3107 non-null   object
 5   condition          3106 non-null   object
 6   benefitsReview     3089 non-null   object
 7   sideEffectsReview  3032 non-null   object
 8   commentsReview     3095 non-null   object
dtypes: int64(2), object(7)
memory usage: 218.6+ KB

In [5]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
Unnamed: 0,3107.0,2080.607016,1187.998828,0.0,1062.5,2092.0,3092.5,4161.0
rating,3107.0,7.006115,2.937582,1.0,5.0,8.0,9.0,10.0

In [6]:
from ydata_profiling import ProfileReport # con este import te hace el EDA DE MANERA AUTOMATICA.

profile = ProfileReport(df, title="Profiling Report")
profile.to_file("drugLibTrain_report.html")

100%|██████████| 9/9 [00:00<00:00, 29.95it/s]00<00:00, 44.64it/s, Describe variable: commentsReview]
Summarize dataset: 100%|██████████| 23/23 [00:00<00:00, 25.13it/s, Completed]
Generate report structure: 100%|██████████| 1/1 [00:02<00:00,  2.49s/it]
Render HTML: 100%|██████████| 1/1 [00:00<00:00,  4.92it/s]
Export report to file: 100%|██████████| 1/1 [00:00<00:00, 153.95it/s]

In [7]:
# Printeo los valores únicos de las columnas categóricas.

print("urlDrugName:", df['urlDrugName'].nunique())
print("effectiveness", df['effectiveness'].nunique())
print("sideEffects:", df['sideEffects'].nunique())
print("condition:", df[ 'condition'].nunique())
print("benefitsReview:", df[ 'benefitsReview'].nunique())
print("sideEffectsReview:", df[ 'sideEffectsReview'].nunique())
print("commentsReview:", df[ 'commentsReview'].nunique())

#las columnas que tiene menos de 10 categorias son 'effectivenessdf' y 'sideEffects'

urlDrugName: 502
effectiveness 5
sideEffects: 5
condition: 1426
benefitsReview: 3031
sideEffectsReview: 2813
commentsReview: 3046

In [8]:
# Nos quedamos con rating (numérica), y las categóricas de menos de 10 categorias.
df_model = df[['rating', 'effectiveness', 'sideEffects']]
df_model

      rating           effectiveness                    sideEffects
0          4        Highly Effective              Mild Side Effects
1          1        Highly Effective            Severe Side Effects
2         10        Highly Effective                No Side Effects
3          3    Marginally Effective              Mild Side Effects
4          2    Marginally Effective            Severe Side Effects
...      ...                     ...                            ...
3102      10        Highly Effective              Mild Side Effects
3103       1             Ineffective  Extremely Severe Side Effects
3104       2    Marginally Effective          Moderate Side Effects
3105       8  Considerably Effective              Mild Side Effects
3106       4    Moderately Effective          Moderate Side Effects

[3107 rows x 3 columns]

#### Transforma las columnas categóricas

Transforma las columnas categoricas a numericas mediante dummies

In [9]:
# Transformamos a dummies con get.dummies
df_model = pd.get_dummies(df_model, columns=['effectiveness', 'sideEffects'])
df_model. info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3107 entries, 0 to 3106
Data columns (total 11 columns):
 #   Column                                     Non-Null Count  Dtype
---  ------                                     --------------  -----
 0   rating                                     3107 non-null   int64
 1   effectiveness_Considerably Effective       3107 non-null   bool
 2   effectiveness_Highly Effective             3107 non-null   bool
 3   effectiveness_Ineffective                  3107 non-null   bool
 4   effectiveness_Marginally Effective         3107 non-null   bool
 5   effectiveness_Moderately Effective         3107 non-null   bool
 6   sideEffects_Extremely Severe Side Effects  3107 non-null   bool
 7   sideEffects_Mild Side Effects              3107 non-null   bool
 8   sideEffects_Moderate Side Effects          3107 non-null   bool
 9   sideEffects_No Side Effects                3107 non-null   bool
 10  sideEffects_Severe Side Effects            3107 non-null   bool
dtypes: bool(10), int64(1)
memory usage: 54.7 KB

#### Evalua cual es la mejor K

Utiliza silhouette_score para evaluar cual es la mejor K.

#### Genera el K Means

In [14]:
from sklearn.cluster import KMeans
X = df_model

# Definimos K_meas, el numero de grupos 
k = 5 # 5 grupos de cosas

# definimos el modelo
kmeans = KMeans(n_clusters=k, n_init=10, random_state=42) 

y_pred = kmeans.fit_predict(X)
#en este modelo no se separa train y test. poruqe no tengo target y no tengo con que compararlo :)

y_pred

array([0, 2, 1, ..., 2, 3, 0], shape=(3107,), dtype=int32)

In [15]:
len(y_pred)

3107

In [18]:
np.unique(y_pred)

array([0, 1, 2, 3, 4], dtype=int32)

In [21]:
# Añadimos la predicción al dataframe
df_model['cluster'] = y_pred

# Echamos un vistazo para ver cómo ha quedado
df_model.head()

,rating,effectiveness_Considerably Effective,effectiveness_Highly Effective,effectiveness_Ineffective,effectiveness_Marginally Effective,effectiveness_Moderately Effective,sideEffects_Extremely Severe Side Effects,sideEffects_Mild Side Effects,sideEffects_Moderate Side Effects,sideEffects_No Side Effects,sideEffects_Severe Side Effects,cluster
0,4,False,True,False,False,False,False,True,False,False,False,0
1,1,False,True,False,False,False,False,False,False,False,True,2
2,10,False,True,False,False,False,False,False,False,True,False,1
3,3,False,False,False,True,False,False,True,False,False,False,2
4,2,False,False,False,True,False,False,False,False,False,True,2

In [ ]:
# Contamos cuántos elementos hay en cada cluster
distribucion = df_model['cluster'].value_counts()

Comprueba los resultados y muestra en un pie plot la distribución de los distintos clusters.

In [32]:
# Configuramos el gráfico
plt.pie(distribucion , labels=distribucion.index, autopct='%1.1f%%')
plt.title('Distribución de clusters')
plt.show() 

#nosé porque no sale el gráfico :(

C:\Users\tifaw\AppData\Local\Temp\ipykernel_17632\421449771.py:4: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()