In [77]:
import sqlite3  # Importamos la librería para trabajar con SQLite
import pandas as pd

In [78]:
# Crear conexión
connect = sqlite3.connect("cervezas.db") #aqui estoy diciendo quiero abrir o crear una base de datos llamada "cervezas.bd", si no existe elarchivo lo crea y si existe lo abre. en mi caso lo crea.
cursor = connect.cursor() #aqui el cursor es quien ejecuta consultas SQL(trae resultados)

In [52]:
#Crear las tablas
##Tabla CERVEZAS
cursor.execute("""
               CREATE TABLE IF NOT EXISTS CERVEZAS(
                   CodC TEXT, -- Código de la cerveza (01, 02, ...)
                   Envase TEXT, -- Tipo de envase (Botella, Lata, Barril)
                   Capacidad FLOAT, -- Capacidad del envase en litros de tipo float
                   Stock INTEGER) -- Cantidad disponible en el almacén de tipo int.
               """)

##Tabla BARES
cursor.execute("""
               CREATE TABLE IF NOT EXISTS BARES( ---Para prevenir errores al ejecutar varias veces, uso IF NOT EXISTS
                CodB TEXT,
                Cif TEXT,
                Nombre TEXT,
                Localidad TEXT)
                """)

##Tabla EMPLEADOS
cursor.execute("""
               CREATE TABLE IF NOT EXISTS EMPLEADOS(
                   CodE INTEGER,
                   Nombre TEXT,
                   Sueldo INTEGER)    
               """)

##Tabla REPARTO
cursor.execute("""
               CREATE TABLE IF NOT EXISTS REPARTO(
                   CodE INTEGER,
                   CodB TEXT,
                   COdC TEXT,
                   Fecha TEXT,
                   Cantidad INTEGER)
                   """)
#GUARDAR LOS CAMBIOS EN LA BBDD
connect.commit() # IMPORTANTE, sin esto, la tabla no se guarda

#COMPROBARMOS QUE La tabla se ha creado correctamente
cursor.execute("SELECT name FROM sqlite_master WHERE type='table';")  # sqlite_master es una tabla interna de SQLite que guarda información de todas las tablas

In [53]:
# Muestra todas las tablas creadas, así podemos confirmar que están creada
print(cursor.fetchall())

[('BARES',), ('EMPLEADOS',), ('REPARTO',), ('CERVEZAS',)]

In [54]:
# INSERTAR Datos en la BASE de datos.

## Datos TABLA CERVEZAS---
"""
Cada INSERT INTO CERVEZAS VALUES(...) agrega una fila con los datos:
'CodC', 'Envase', Capacidad en litros, Stock disponible
"""
cursor.execute("INSERT INTO CERVEZAS VALUES('01', 'Botella', 0.2, 3600)")
cursor.execute("INSERT INTO CERVEZAS VALUES ('02','Botella',0.33,1200)")
cursor.execute("INSERT INTO CERVEZAS VALUES ('03','Lata',0.33,2400)")
cursor.execute("INSERT INTO CERVEZAS VALUES ('04','Botella',1,288)")
cursor.execute("INSERT INTO CERVEZAS VALUES ('05','Barril',60,30)")

## Datos TABLA BARES---
""" 
Cada fila tiene: 'CodB', 'Cif', 'Nombre', 'Localidad'
"""
cursor.execute("INSERT INTO BARES VALUES('001', '11111111X', 'Stop', 'Villa Botijo')")
cursor.execute("INSERT INTO BARES VALUES ('002','22222222Y','Las Vegas','Villa Botijo')")
cursor.execute("INSERT INTO BARES VALUES ('003','-','Club Social','Las Ranas')")
cursor.execute("INSERT INTO BARES VALUES ('004','33333333Z','Otra Ronda','La Esponja')")

## Datos TABLA EMPLEADOS---
"""
Cada fila tiene: 'CodE', 'Nombre', 'Sueldo'
"""
cursor.execute("INSERT INTO EMPLEADOS VALUES(1, 'Prudencio Caminero', 120000)")
cursor.execute("INSERT INTO EMPLEADOS VALUES(2, 'Vicente Merario', 110000)")
cursor.execute("INSERT INTO EMPLEADOS VALUES(3, 'Valentin Siempre', 100000)")

## Datos TABLA REPARTO
"""
Cada fila tiene: 'CodE', 'CodB', 'CodC', 'Fecha', 'Cantidad'
Representa un reparto hecho por un empleado a un bar de cierta cerveza
"""
cursor.execute("INSERT INTO REPARTO VALUES(1, '001', '01', '10/21/05', 240)")
cursor.execute("INSERT INTO REPARTO VALUES(1, '001', '02', '10/21/05', 48)")
cursor.execute("INSERT INTO REPARTO VALUES(1, '002', '03', '10/22/05', 60)")
cursor.execute("INSERT INTO REPARTO VALUES(1, '004', '05', '10/22/05', 4)")
cursor.execute("INSERT INTO REPARTO VALUES(2, '002', '03', '10/22/05', 48)")
cursor.execute("INSERT INTO REPARTO VALUES(2, '002', '05', '10/23/05', 2)")
cursor.execute("INSERT INTO REPARTO VALUES(2, '004', '01', '10/23/05', 480)")
cursor.execute("INSERT INTO REPARTO VALUES(2, '004', '02', '10/24/05', 72)")
cursor.execute("INSERT INTO REPARTO VALUES(3, '003', '03', '10/24/05', 48)")
cursor.execute("INSERT INTO REPARTO VALUES(3, '003', '04', '10/25/05', 20)")

#GUARDAR CAMBIOS
connect.commit() # Guarda todos los inserts en la BBDD

In [59]:
#Ejecuta este código para ver cuántas filas hay en la tabla REPARTO:
cursor.execute("SELECT COUNT(*) FROM REPARTO")
print("Número total de filas en REPARTO:", cursor.fetchone()[0])
#Ejecuta este código para ver cuántas filas hay en la tabla CERVEZAS:
cursor.execute("SELECT COUNT(*) FROM CERVEZAS")
print("Número total de filas en CERVEZAS:", cursor.fetchone()[0])
#Ejecuta este código para ver cuántas filas hay en la tabla BARES:
cursor.execute("SELECT COUNT(*) FROM BARES")
print("Número total de filas en BARES:", cursor.fetchone()[0])
#Ejecuta este código para ver cuántas filas hay en la tabla EMPLEADOS:
cursor.execute("SELECT COUNT(*) FROM EMPLEADOS")
print("Número total de filas en EMPLEADOS:", cursor.fetchone()[0])

Número total de filas en REPARTO: 10
Número total de filas en CERVEZAS: 5
Número total de filas en BARES: 4
Número total de filas en EMPLEADOS: 3

## 2. Enunciados de los Ejercicios
1. Obtener el nombre de los empleados que hayan repartido al bar **Stop** durante la semana del 17 al 23 de octubre de 2005.
2. Obtener el Cif y nombre de los bares a los que se ha repartido cerveza de tipo **Botella** y capacidad inferior a 1 litro, ordenados por localidad.
3. Obtener los repartos (nombre del bar, envase y capacidad de la bebida, fecha y cantidad) realizados por **Prudencio Caminero**.
4. Obtener los bares a los que se les ha repartido envases de tipo **botella** y capacidad 0.2 ó 0.33.
5. Nombre de los empleados que han repartido a los bares **"Stop"** y **"Las Vegas"** cervezas con envase botella. 
6. Obtener el nombre y número de viajes que ha realizado cada empleado fuera de **Villa Botijo**.
7. Obtener el nombre y localidad del bar que más litros de cerveza ha comprado.
8. Obtener los bares que han adquirido todos los tipos de cerveza con envase de botella y capacidad menor que 1 litro.
9. Subir un 5% el sueldo del empleado que más días haya trabajado.
10. Insertar un nuevo reparto del empleado **"Vicente Merario"** al bar **"Stop"** de 48 cervezas de tipo lata el día 10/26/05.

In [55]:
# Función para ejecutar una consulta SQL y devolver un DataFrame
def sql_query(query, cursor):
    """
    Ejecuta una query SQL usando el cursor proporcionado
    y devuelve los resultados como un DataFrame de Pandas.

    Parámetros:
    - query : str : La consulta SQL a ejecutar
    - cursor : sqlite3.Cursor : Cursor de la conexión a la base de datos

    Retorna:
    - pd.DataFrame con los resultados de la consulta
    """
    # Ejecutamos la consulta SQL
    cursor.execute(query)

    # Guardamos los resultados en una lista de tuplas
    resultados = cursor.fetchall()

    # Obtenemos los nombres de las columnas de la consulta
    columnas = [descripcion[0] for descripcion in cursor.description]

    # Convertimos los resultados a un DataFrame de Pandas y devolvemos
    return pd.DataFrame(resultados, columns=columnas)

1. Obtener el nombre de los empleados que hayan repartido al bar **Stop** durante la semana del 17 al 23 de octubre de 2005.

In [56]:
#Ejecutar consulta
cursor.execute("""
SELECT DISTINCT EMPLEADOS.Nombre
FROM REPARTO
JOIN EMPLEADOS ON REPARTO.CodE = EMPLEADOS.CodE
JOIN BARES ON REPARTO.CodB = BARES.CodB
WHERE BARES.Nombre = 'Stop'
    AND REPARTO.Fecha BETWEEN '17/10/05' AND '23/10/05';
""")

# Aplico la funcion
df_empleados_stop = sql_query("""
SELECT DISTINCT EMPLEADOS.Nombre
FROM REPARTO
JOIN EMPLEADOS ON REPARTO.CodE = EMPLEADOS.CodE ---JOIN para conectar las tablas con sus claves.
JOIN BARES ON REPARTO.CodB = BARES.CodB
WHERE BARES.Nombre = 'Stop'
  AND REPARTO.Fecha BETWEEN '10/17/05' AND '10/23/05';
""", cursor)

# Mostramos el resultado
df_empleados_stop

               Nombre
0  Prudencio Caminero

2. Obtener el Cif y nombre de los bares a los que se ha repartido cerveza de tipo **Botella** y capacidad inferior a 1 litro, ordenados por localidad.

In [57]:
#Ejecutar consulta
cursor. execute("""
                SELECT DISTINCT BARES.Cif, BARES.Nombre ---DISTINCT para que no repita bares si tienen varios repartos que cumplen la condición.
                FROM REPARTO
                JOIN BARES ON REPARTO.CodB = BARES.CodB ---JOIN para conectar las tablas con sus claves.
                JOIN CERVEZAS ON REPARTO.CodC = Cervezas.CodC
                WHERE CERVEZAS.Envase = 'Botella'
                    AND CERVEZAS.Capacidad < 1
                ORDER BY BARES.Localidad;
                """)
# Aplico la funcion
df_bares_botella = sql_query("""
                SELECT DISTINCT BARES.Cif, BARES.Nombre ---DISTINCT para que no repita bares si tienen varios repartos que cumplen la condición.
                FROM REPARTO
                JOIN BARES ON REPARTO.CodB = BARES.CodB ---JOIN para conectar las tablas con sus claves.
                JOIN CERVEZAS ON REPARTO.CodC = Cervezas.CodC
                WHERE CERVEZAS.Envase = 'Botella'
                    AND CERVEZAS.Capacidad < 1
                ORDER BY BARES.Localidad;
                """, cursor)

# Mostramos el resultado
df_bares_botella

         Cif      Nombre
0  33333333Z  Otra Ronda
1  11111111X        Stop

3. Obtener los repartos (nombre del bar, envase y capacidad de la bebida, fecha y cantidad) realizados por **Prudencio Caminero**.

In [ ]:
#construiR la consulta:
"""
SELECT BARES.Nombre, CERVEZAS.Envase, CERVEZAS.Capacidad, REPARTO.Fecha, REPARTO.Cantidad
FROM REPARTO
JOIN EMPLEADOS ON REPARTO.CodE = EMPLEADOS.CodE
JOIN BARES ON REPARTO.CodB = BARES.CodB
JOIN CERVEZAS ON REPARTO.CodC = CERVEZAS.CodC
WHERE EMPLEADOS.Nombre = 'Prudencio Caminero';

"""
# Aplico la funcion
df_repartos_prudencio = sql_query("""
                SELECT BARES.Nombre, CERVEZAS.Envase, CERVEZAS.Capacidad, REPARTO.Fecha, REPARTO.Cantidad
                FROM REPARTO
                JOIN EMPLEADOS ON REPARTO.CodE = EMPLEADOS.CodE
                JOIN BARES ON REPARTO.CodB = BARES.CodB
                JOIN CERVEZAS ON REPARTO.CodC = CERVEZAS.CodC
                WHERE EMPLEADOS.Nombre = 'Prudencio Caminero';

                """, cursor)

# Mostramos el resultado
df_repartos_prudencio

       Nombre   Envase  Capacidad     Fecha  Cantidad
0        Stop  Botella       0.20  10/21/05       240
1        Stop  Botella       0.33  10/21/05        48
2   Las Vegas     Lata       0.33  10/22/05        60
3  Otra Ronda   Barril      60.00  10/22/05         4

4. Obtener los bares a los que se les ha repartido envases de tipo **botella** y capacidad 0.2 ó 0.33.

In [62]:
#construiR la consulta:
"""
SELECT BARES.Nombre
FROM REPARTO
JOIN BARES ON REPARTO.CodB = BARES.CodB
JOIN CERVEZAS ON REPARTO.CodC = CERVEZAS.CodC
WHERE CERVEZAS.Envase = 'Botella'
    AND CERVEZAS.Capacidad IN (0.2, 0.33)
ORDER BY BARES.Nombre;
    
"""
# Aplico la funcion
df_bares_botella_peq = sql_query("""
                SELECT BARES.Nombre
                FROM REPARTO
                JOIN BARES ON REPARTO.CodB = BARES.CodB
                JOIN CERVEZAS ON REPARTO.CodC = CERVEZAS.CodC
                WHERE CERVEZAS.Envase = 'Botella'
                    AND CERVEZAS.Capacidad IN (0.2, 0.33)
                ORDER BY BARES.Nombre;
                """, cursor)

# Mostramos el resultado
df_bares_botella_peq

       Nombre
0  Otra Ronda
1  Otra Ronda
2        Stop
3        Stop

5. Nombre de los empleados que han repartido a los bares **"Stop"** y **"Las Vegas"** cervezas con envase botella.

In [64]:
#construiR la consulta:
"""
SELECT EMPLEADOS.Nombre
FROM REPARTO
JOIN BARES ON REPARTO.CodB = BARES.CodB
JOIN CERVEZAS ON REPARTO.CodC = CERVEZAS.CodC
JOIN EMPLEADOS ON REPARTO.CodE = EMPLEADOS.CodE
WHERE BARES.Nombre IN ('Stop', 'Vegas')
    AND CERVEZAS.Envase = 'Botella'
GROUP BY EMPREADOS.Nombre;
    
"""
# Aplico la funcion
df_empleados_stop_vegas = sql_query("""
                SELECT EMPLEADOS.Nombre
                FROM REPARTO
                JOIN BARES ON REPARTO.CodB = BARES.CodB
                JOIN CERVEZAS ON REPARTO.CodC = CERVEZAS.CodC
                JOIN EMPLEADOS ON REPARTO.CodE = EMPLEADOS.CodE
                WHERE BARES.Nombre IN ('Stop', 'Vegas')
                    AND CERVEZAS.Envase = 'Botella'
                GROUP BY EMPLEADOS.Nombre;
                """, cursor)

# Mostramos el resultado
df_empleados_stop_vegas

               Nombre
0  Prudencio Caminero

6. Obtener el nombre y número de viajes que ha realizado cada empleado fuera de **Villa Botijo**.

In [70]:
#construiR la consulta:
"""
SELECT EMPLEADO.Nombre, COUNT(*) AS NumeroViajes
FROM REPARTO
JOIN EMPLEADO ON REPARTO.CodE =EMPLEADO.CodE
JOIN BARES ON REPARTO.CodB = BARES.CodB
WHERE BARES.Localidad != 'Villa Botijo'
GROUP BY EMPLEADOS.Nombre
ORDER BY EMPLEADOS.Nombre;
"""

# Aplico la funcion
df_viajes_fuera  = sql_query("""
                SELECT EMPLEADOS.Nombre, COUNT(*) AS NumeroViajes
                FROM REPARTO
                JOIN EMPLEADOS ON REPARTO.CodE =EMPLEADOS.CodE
                JOIN BARES ON REPARTO.CodB = BARES.CodB
                WHERE BARES.Localidad != 'Villa Botijo'
                GROUP BY EMPLEADOS.Nombre
                ORDER BY EMPLEADOS.Nombre;
                """, cursor)
# Mostramos el resultado
df_viajes_fuera

               Nombre  NumeroViajes
0  Prudencio Caminero             1
1    Valentin Siempre             2
2     Vicente Merario             2

7. Obtener el nombre y localidad del bar que más litros de cerveza ha comprado.

In [71]:
#construiR la consulta:
"""
SELECT BARES.Nombre, BARES.Localidad, SUM(REPARTO.Cantidad * CERVEZAS.Capacidad) AS LitrosTotales
FROM REPARTO
JOIN BARES ON REPARTO.CodB = BARES.CodB
JOIN CERVEZAS ON REPARTO.CodC = CERVEZAS.CodC
GROUP BY BARES.Nombre, BARES.Localidad
"""
# Aplico la funcion
df_bar_max_litros = sql_query("""
SELECT BARES.Nombre, BARES.Localidad, SUM(REPARTO.Cantidad * CERVEZAS.Capacidad) AS LitrosTotales
FROM REPARTO
JOIN BARES ON REPARTO.CodB = BARES.CodB
JOIN CERVEZAS ON REPARTO.CodC = CERVEZAS.CodC
GROUP BY BARES.Nombre, BARES.Localidad
""", cursor)
# Mostramos el resultado
df_bar_max_litros

        Nombre     Localidad  LitrosTotales
0  Club Social     Las Ranas          35.84
1    Las Vegas  Villa Botijo         155.64
2   Otra Ronda    La Esponja         359.76
3         Stop  Villa Botijo          63.84

8. Obtener los bares que han adquirido todos los tipos de cerveza con envase de botella y capacidad menor que 1 litro.

In [ ]:
#construiR la consulta:
"""
SELECT BARES.Nombre
FROM REPARTO
JOIN BARES ON REPARTO.CodB = Bares.CodB
JOIN CERVEZAS ON REPARTO.CodC = CERVEZAS.CodC
WHERE CERVEZAS.Envase = 'Botella'
    AND CERVEZAS.Capacidad < 1
GROUP BY BARES.Nombre
HAVING COUNT(DISTINCT CERVEZAS.Capacidad) = 2; 
"""
"""HAVING COUNT(DISTINCT CERVEZAS.Capacidad) = 2 #HAVING: filtra los grupos (después del GROUP BY),COUNT(...): cuenta cuántos valores hay,2: queremos solo los bares que tengan 2 capacidades distintas"""

# Aplico la funcion
df_bares_completos = sql_query("""
                              SELECT BARES.Nombre
                                FROM REPARTO
                                JOIN BARES ON REPARTO.CodB = Bares.CodB
                                JOIN CERVEZAS ON REPARTO.CodC = CERVEZAS.CodC
                                WHERE CERVEZAS.Envase = 'Botella'
                                    AND CERVEZAS.Capacidad < 1
                                GROUP BY BARES.Nombre
                                HAVING COUNT(DISTINCT CERVEZAS.Capacidad) = 2; 
                                """, cursor)
# Mostramos el resultado
df_bares_completos

       Nombre
0  Otra Ronda
1        Stop

9. Subir un 5% el sueldo del empleado que más días haya trabajado.

In [ ]:
#construiR la consulta:
#PRIMERO ENCONTRAR EMPLEADO QUE MAS HA TRABAJADO

"""
SELECT CodE
FROM REPARTO
GROUP BY CodE --- agrupa por empleado
Order by COUNT(*) DESC --- cuénta cuantos repartos hizo
LIMIT 1; --- el que más tiene
"""
#segundo subir el sueldo, aqui mi función sql_query() NO sirve para UPDATE. solo funciona con consultas SELECT
cursor.execute("""
            UPDATE EMPLEADOS
            SET Sueldo = Sueldo * 1.05
            WHERE CodE =(SELECT CodE
                        FROM REPARTO
                        GROUP BY CodE --- agrupa por empleado
                        Order by COUNT(*) DESC --- cuénta cuantos repartos hizo
                        LIMIT 1);--- el que más tiene
            """)
                        
connect.commit()

#comprobar el Update

df_empleados = sql_query("SELECT * FROM EMPLEADOS", cursor)
df_empleados

   CodE              Nombre  Sueldo
0     1  Prudencio Caminero  120000
1     2     Vicente Merario  115500
2     3    Valentin Siempre  100000

10. Insertar un nuevo reparto del empleado **"Vicente Merario"** al bar **"Stop"** de 48 cervezas de tipo lata el día 10/26/05.

In [81]:
# En reparto uso codigos
"""
EL ORDEN EN QUE IRAN ESTOS DATOS LUEGO DEBE COINCIDIR CON LAS COLUMNAS:| CodE | CodB | CodC | Fecha | Cantidad
Vcente Merario => CodE = 2
Stop => CodB = 001
Lata => en CERVEZAS => CodC = 03
Fecha => '10/26/05'
Cantidad = 48 
"""
#ejecutar código
cursor.execute("""
               INSERT INTO REPARTO VALUES(2, '001', '03','10/26/05',48);
               """)
connect.commit()

In [82]:
#COMPROBAR QUE SE HA HECHO EL CAMBIO 
df_reparto = sql_query("SELECT * FROM REPARTO", cursor)
df_reparto

    CodE CodB COdC     Fecha  Cantidad
0      1  001   01  10/21/05       240
1      1  001   02  10/21/05        48
2      1  002   03  10/22/05        60
3      1  004   05  10/22/05         4
4      2  002   03  10/22/05        48
5      2  002   05  10/23/05         2
6      2  004   01  10/23/05       480
7      2  004   02  10/24/05        72
8      3  003   03  10/24/05        48
9      3  003   04  10/25/05        20
10     2  001   03  10/26/05        48